// catalog.js  —  MUSS JS sein (nicht JSON!)
window.catalog = [
  // ===== VIDEOS MIT QUELLEN (inkl. Setlists) =====
  {
    id: "wembley88",
    title: "Wembley, London (July 16, 1988)",
    poster: "wembley88.jpg",
    source: "https://stream.mux.com/psiaSdHvwfUNwr009HByfodmnXmwVWHK1EFqGIokLUa00.m3u8",
    mp4:    "https://stream.mux.com/psiaSdHvwfUNwr009HByfodmnXmwVWHK1EFqGIokLUa00/medium.mp4",
    type: "hls",
    category: "live",
    tier: "pro",
    chapters: [
      { sec:   0, label: "PLAY ALL" },
      { sec: 107, label: "INTRO" },
      { sec: 193, label: "WANNA BE STARTIN' SOMETHIN" },
      { sec: 503, label: "HEARTBREAK HOTEL" },
      { sec: 798, label: "ANOTHER PART OF ME" },
      { sec:1051, label: "I JUST CAN'T STOP LOVING YOU" },
      { sec:1352, label: "SHE'S OUT OF MY LIFE" },
      { sec:1583, label: "I WANT YOU BACK" },
      { sec:1647, label: "THE LOVE YOU SAVE" },
      { sec:1707, label: "I'LL BE THERE" },
      { sec:2018, label: "ROCK WITH YOU" },
      { sec:2280, label: "HUMAN NATURE" },
      { sec:2654, label: "SMOOTH CRIMINAL" },
      { sec:3021, label: "DIRTY DIANA" },
      { sec:3413, label: "THRILLER" },
      { sec:3693, label: "BAND GROOVE" },
      { sec:4528, label: "WORKING' DAY AND NIGHT" },
      { sec:5004, label: "BEAT IT" },
      { sec:5412, label: "BILLIE JEAN" },
      { sec:5977, label: "BAD" },
      { sec:6548, label: "MAN IN THE MIRROR" },
      { sec:7102, label: "THE WAY YOU MAKE ME FEEL (BONUS)" }
    ]
  },
  {
    id: "oslo92",
    title: "Oslo, Norway (July 15, 1992)",
    poster: "oslo92.jpg",
    source: "https://stream.mux.com/eilh02VSicPAlaMo8QsyeA8hBeJooIvNQ7r81oy4AffM.m3u8",
    mp4:    "https://stream.mux.com/eilh02VSicPAlaMo8QsyeA8hBeJooIvNQ7r81oy4AffM/medium.mp4",
    type: "hls",
    category: "live",
    tier: "pro",
    chapters: [
      { sec:   0, label: "PLAY ALL" },
      { sec: 114, label: "JAM" },
      { sec: 503, label: "WANNA BE STARTIN' SOMETHIN" },
      { sec: 847, label: "HUMAN NATURE" },
      { sec:1191, label: "SMOOTH CRIMINAL" },
      { sec:1566, label: "I JUST CAN'T STOP LOVING YOU" },
      { sec:1875, label: "SHE'S OUT OF MY LIFE" },
      { sec:2141, label: "THE JACKSON 5 MEDLEY" },
      { sec:2542, label: "THRILLER" },
      { sec:2897, label: "BILLIE JEAN" },
      { sec:3335, label: "WORKIN' DAY AND NIGHT" },
      { sec:3806, label: "BEAT IT" },
      { sec:4342, label: "WILL YOU BE THERE" },
      { sec:4837, label: "THE WAY YOU MAKE ME FEEL" },
      { sec:5199, label: "BAD" },
      { sec:5634, label: "BLACK OR WHITE" },
      { sec:6196, label: "HEAL THE WORLD" },
      { sec:6692, label: "MAN IN THE MIRROR" }
    ]
  },
  {
    id: "copen92",
    title: "Copenhagen, Denmark (Aug 20, 1992)",
    poster: "copen92.jpg",
    source: "https://stream.mux.com/01S01yRyiHjrZq00N4UUyiUfd00K01ndiVaNLfo02mY5Php01s.m3u8",
    mp4:    "https://stream.mux.com/01S01yRyiHjrZq00N4UUyiUfd00K01ndiVaNLfo02mY5Php01s/medium.mp4",
    type: "hls",
    category: "live",
    tier: "pro",
    chapters: [
      { sec:   0, label: "PLAY ALL" },
      { sec:  93, label: "JAM" },
      { sec: 504, label: "WANNA BE STARTIN' SOMETHIN" },
      { sec: 889, label: "HUMAN NATURE" },
      { sec:1219, label: "SMOOTH CRIMINAL" },
      { sec:1685, label: "I JUST CAN'T STOP LOVING YOU" },
      { sec:1980, label: "SHE'S OUT OF MY LIFE" },
      { sec:2243, label: "THE JACKSON 5 MEDLEY" },
      { sec:2662, label: "THRILLER" },
      { sec:2996, label: "BILLIE JEAN" },
      { sec:3443, label: "WORKIN' DAY AND NIGHT" },
      { sec:3954, label: "BEAT IT" },
      { sec:4545, label: "WILL YOU BE THERE" },
      { sec:4975, label: "BLACK OR WHITE" },
      { sec:5471, label: "HEAL THE WORLD" },
      { sec:6082, label: "MAN IN THE MIRROR" }
    ]
  },
{
  id: "tokyo88",
  title: "Tokyo, Japan (December 9, 1988)",
  poster: "tokyo88.jpg",
  source: "https://stream.mux.com/7cygwCLYFLVeBQl5faq5HdctzRdSsXMM02wRuyF6ixeE.m3u8",
  mp4:    "https://stream.mux.com/7cygwCLYFLVeBQl5faq5HdctzRdSsXMM02wRuyF6ixeE/medium.mp4",
  type: "hls",
  category: "live",
  tier: "pro",
  chapters: [
    { sec:   0, label: "PLAY ALL" },
    { sec:   0, label: "INTRO" },
    { sec:  77, label: "WANNA BE STARTIN' SOMETHIN" },
    { sec: 380, label: "HEARTBREAK HOTEL" },
    { sec: 681, label: "ANOTHER PART OF ME" },
    { sec: 921, label: "HUMAN NATURE" },
    { sec:1280, label: "SMOOTH CRIMINAL" },
    { sec:1644, label: "I JUST CAN'T STOP LOVING YOU (INCOMPLETE)" }
  ]
},
{
  id: "brisbane87",
  title: "Brisbane, Australia (November 28, 1987)",
  poster: "brisbane87.jpg",
  source: "https://stream.mux.com/LMGpGcNPaNTbPoqobB8y8i2gKDYxmilMxj702O5agUi4.m3u8",
  mp4:    "https://stream.mux.com/LMGpGcNPaNTbPoqobB8y8i2gKDYxmilMxj702O5agUi4/medium.mp4",
  type: "hls",
  category: "live",
  tier: "pro",
  chapters: [
    { sec:   0,  label: "PLAY ALL" },
    { sec:  45,  label: "WANNA BE STARTIN' SOMETHIN" },
    { sec: 366,  label: "THINGS I DO FOR YOU" },
    { sec: 583,  label: "OFF THE WALL" },
    { sec: 823,  label: "HUMAN NATURE" },
    { sec:1189,  label: "THIS PLACE HOTEL" },
    { sec:1500,  label: "SHE'S OUT OF MY LIFE" },
    { sec:1754,  label: "JACKSON 5 MEDLEY" },
    { sec:2143,  label: "ROCK WITH YOU" },
    { sec:2390,  label: "LOVELY ONE" }
  ]
},
{
  id: "beunos93",
  title: "Buenos Aires, Argentina (October 10, 1993)",
  poster: "beunos93.jpg",
  source: "https://stream.mux.com/yihD6aJBmgrHe8yrJWx9z9OLooy6UoWiXVQldUUBlm4.m3u8",
  mp4:    "https://stream.mux.com/yihD6aJBmgrHe8yrJWx9z9OLooy6UoWiXVQldUUBlm4/medium.mp4",
  type: "hls",
  category: "live",
  tier: "pro",
  chapters: [
    { sec:    0, label: "PLAY ALL" },
    { sec:  366, label: "JAM" },
    { sec:  831, label: "WANNA BE STARTIN' SOMETHIN'" },
    { sec: 1274, label: "HUMAN NATURE" },
    { sec: 1658, label: "SMOOTH CRIMINAL" },
    { sec: 2235, label: "I JUST CAN'T STOP LOVING YOU" },
    { sec: 2546, label: "SHE'S OUT OF MY LIFE" },
    { sec: 2940, label: "THE JACKSON 5 MEDLEY" },
    { sec: 3453, label: "THRILLER" },
    { sec: 3863, label: "BILLIE JEAN" },
    { sec: 4670, label: "WILL YOU BE THERE" },
    { sec: 5264, label: "DANGEROUS" },
    { sec: 5615, label: "BLACK OR WHITE" },
    { sec: 6345, label: "HEAL THE WORLD" }
  ]
},
{
  id: "yokohama87",
  title: "Yokohama, Japan (September 26, 1987)",
  poster: "yokohama87.jpg",
  source: "https://video-v2.jottacloud.com/playlist/eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NjAwMzI4MDAwMDAsInVzZXJuYW1lIjoiczh2aG5uMm9rZm9ibmN1d3dhaXluOTlqIiwibWQ1IjoiZWQ5NzQ1OTg4Yzc4NTViNDhjOGQzMzRjZGViNmY3YjcifQ.ASVLrZiyzgibkQTqc4DWYdcwAsGzP1xXvdkjLfpTs4k.m3u8?q=hd",
  mp4:    "https://jottacloud.com/web/sync/list/name/MJ%20-%201987%20Bad%20Tour%20Yokohama%2C%20Japan%201987.mp4",
  type: "hls",
  category: "live",
  tier: "pro",
  chapters: [
    { sec:    0,   label: "PLAY ALL" },
    { sec:  107,   label: "WANNA BE STARTIN' SOMETHIN" },
    { sec:  423,   label: "THINGS I DO FOR YOU" },
    { sec:  632,   label: "OFF THE WALL" },
    { sec:  859,   label: "HUMAN NATURE" },
    { sec: 1188,   label: "HEARTBREAK HOTEL" },
    { sec: 1456,   label: "SHE'S OUT OF MY LIFE" },
    { sec: 1718,   label: "I WANT YOU BACK" },
    { sec: 1782,   label: "THE LOVE YOU SAVE" },
    { sec: 1841,   label: "I'LL BE THERE" },
    { sec: 2099,   label: "ROCK WITH YOU" },
    { sec: 2343,   label: "YOU ARE MY LOVELY ONE" },
    { sec: 2709,   label: "WORKING DAY AND NIGHT" },
    { sec: 3142,   label: "BEAT IT" },
    { sec: 3532,   label: "BILLIE JEAN" },
    { sec: 3845,   label: "SHAKE YOUR BODY" },
    { sec: 4659,   label: "THRILLER" },
    { sec: 4919,   label: "I JUST CAN'T STOP LOVING YOU" },
    { sec: 5318,   label: "BAD" }
  ]
},
{
  id: "toronto84",
  title: "Toronto, Canada (October 5, 1984)",
  poster: "toronto84.jpg",
  source: "https://stream.mux.com/kIXKYxBGnLPBnDdoLMjrhdGxvmf3mtIngjdz1KTfga4.m3u8",
  mp4:    "https://stream.mux.com/kIXKYxBGnLPBnDdoLMjrhdGxvmf3mtIngjdz1KTfga4/medium.mp4",
  type: "hls",
  category: "live",
  tier: "pro",
  chapters: [
    { sec:    0,   label: "PLAY ALL" },
    { sec:    0,   label: "SWORD IN THE STONE INTRO" },
    { sec:  520,   label: "WANNA BE STARTIN' SOMETHIN" },
    { sec:  846,   label: "THINGS I DO FOR YOU" },
    { sec: 1075,   label: "OFF THE WALL" },
    { sec: 1367,   label: "HUMAN NATURE" },
    { sec: 1608,   label: "THIS PLACE HOTEL" },
    { sec: 1923,   label: "SHE'S OUT OF MY LIFE" },
    { sec: 2195,   label: "JERMAINE JACKSON MEDLEY" },
    { sec: 2964,   label: "JACKSON 5 MEDLEY" },
    { sec: 3408,   label: "ROCK WITH YOU" },
    { sec: 3664,   label: "LOVELY ONE" },
    { sec: 4063,   label: "WORKING DAY AND NIGHT" },
    { sec: 4827,   label: "BEAT IT" },
    { sec: 5332,   label: "BILLIE JEAN" },
    { sec: 5730,   label: "SHAKE YOUR BODY" }
  ]
},

  // ===== RESTLICHE POSTER (ohne Quellen, werden trotzdem angezeigt) =====
  { id:"bucharest92",   title:"Bucharest 92",   poster:"bucharest92.jpg",   source:"", type:"hls", category:"live", tier:"pro" },
  { id:"beunos93",      title:"Buenos Aires 93",poster:"beunos93.jpg",      source:"", type:"hls", category:"live", tier:"pro" },

  {
    id:"bremen92",
    title:"Bremen, Germany (August 8, 1992)",
    poster:"bremen92.jpg",
    source:"https://stream.mux.com/lmlqCHwctsaom44AldB02lyE8dWsa51NGXHBAM01i56aw.m3u8",
    mp4:   "https://stream.mux.com/lmlqCHwctsaom44AldB02lyE8dWsa51NGXHBAM01i56aw/medium.mp4",
    type:"hls",
    category:"live",
    tier:"pro",
    chapters: [
      { label: "PLAY ALL", sec: 0 },
      { label: "INTRO", sec: 0 },
      { label: "JAM", sec: 308 },
      { label: "WANNA BE STARTIN' SOMETHIN'", sec: 699 },
      { label: "HUMAN NATURE", sec: 1055 },
      { label: "SMOOTH CRIMINAL", sec: 1393 },
      { label: "I JUST CAN'T STOP LOVING YOU", sec: 1835 },
      { label: "SHE'S OUT OF MY LIFE", sec: 2133 },
      { label: "THE JACKSON 5 MEDLEY", sec: 2420 },
      { label: "THRILLER", sec: 2836 },
      { label: "BILLIE JEAN", sec: 3188 },
      { label: "WORKIN' DAY AND NIGHT", sec: 3836 },
      { label: "BEAT IT", sec: 4376 },
      { label: "WILL YOU BE THERE", sec: 5002 },
      { label: "BLACK OR WHITE", sec: 5528 },
      { label: "HEAL THE WORLD", sec: 6028 },
      { label: "MAN IN THE MIRROR", sec: 6660 }
    ]
  },
  {
    id:"rome88",
    title:"Rome, Italy (May 23, 1988)",
    poster:"rome88.jpg",
    source:"https://video-v2.jottacloud.com/playlist/eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3NjAwMzI4MDAwMDAsInVzZXJuYW1lIjoiczh2aG5uMm9rZm9ibmN1d3dhaXluOTlqIiwibWQ1IjoiODAyYmFlYmMwMWQ0ZjQ2ZGU2Mzc3M2FmMzcxODRmYjAifQ.v6ZXu0burlOZpNFefuNcyTb8h-n8N8nOyiPr4GXbFKQ.m3u8?q=hd",
    type:"hls",
    category:"live",
    tier:"pro",
    chapters: [
      { label: "INTRO", sec: 50 },
      { label: "WANNA BE STARTIN' SOMETHIN'", sec: 132 },
      { label: "HEARTBREAK HOTEL", sec: 447 },
      { label: "ANOTHER PART OF ME", sec: 744 },
      { label: "I JUST CAN'T STOP LOVING YOU", sec: 1016 },
      { label: "SHE'S OUT OF MY LIFE", sec: 1299 },
      { label: "I WANT YOU BACK", sec: 1517 },
      { label: "THE LOVE YOU SAVE", sec: 1582 },
      { label: "I'LL BE THERE", sec: 1643 },
      { label: "ROCK WITH YOU", sec: 1872 },
      { label: "HUMAN NATURE", sec: 2142 },
      { label: "SMOOTH CRIMINAL (INTRO)", sec: 2459 },
      { label: "SMOOTH CRIMINAL", sec: 2521 },
      { label: "DIRTY DIANA", sec: 2907 },
      { label: "THRILLER", sec: 3319 }
    ]
  },

  { id:"tokyo87",       title:"Tokyo 87",       poster:"tokyo87.jpg",       source:"", type:"hls", category:"live", tier:"pro" },
  { id:"yokohama87",    title:"Yokohama 87",    poster:"yokohama87.jpg",    source:"", type:"hls", category:"live", tier:"pro" },
  { id:"auckland96",    title:"Auckland 96",    poster:"auckland96.jpg",    source:"", type:"hls", category:"live", tier:"pro" },
  { id:"basel97",       title:"Basel 97",       poster:"basel97.jpg",       source:"", type:"hls", category:"live", tier:"pro" },
  { id:"bucharest96",   title:"Bucharest 96",   poster:"bucharest96.jpg",   source:"https://stream.mux.com/Om7y481gzPH00TZ6DVl5NpmSVGrqJMJbvz17dmVVn00yA.m3u8", type:"hls", category:"live", tier:"pro" },
  { id:"copenhagen97",  title:"Copenhagen 97",  poster:"copenhagen97.jpg",  source:"", type:"hls", category:"live", tier:"pro" },
  { id:"gothenburg97",  title:"Gothenburg 97",  poster:"gothenburg97.jpg",  source:"", type:"hls", category:"live", tier:"pro" },
  { id:"helsinki97",    title:"Helsinki 97",    poster:"helsinki97.jpg",    source:"", type:"hls", category:"live", tier:"pro" },
  { id:"johannesburg97",title:"Johannesburg 97",poster:"johannesburg97.jpg",source:"", type:"hls", category:"live", tier:"pro" },
  { id:"kualalumpur96", title:"Kuala Lumpur 96",poster:"kualalumpur96.jpg", source:"", type:"hls", category:"live", tier:"pro" },
  { id:"munich97",      title:"Munich 97",      poster:"munich97.jpg",      source:"", type:"hls", category:"live", tier:"pro" },
  { id:"seoul96",       title:"Seoul 96",       poster:"seoul96.jpg",       source:"", type:"hls", category:"live", tier:"pro" },

  // neue Poster + AM/PRO Markierungen
  { id:"barcelona88",   title:"Barcelona 88",   poster:"barcelona88.jpg",   source:"", type:"hls", category:"live", tier:"am"  },
  { id:"royalbrunei96", title:"Brunei 96 (Royal Celebration)", poster:"royalbrunei96.jpg", source:"", type:"hls", category:"live", tier:"pro" },
  { id:"brunei96htw",   title:"Brunei 96 – Heal The World",    poster:"brunei96htw.jpg",   source:"", type:"hls", category:"live", tier:"pro" },
  { id:"monza92",       title:"Monza 92",      poster:"monza92.jpg",       source:"", type:"hls", category:"live", tier:"am"  },
  { id:"london79",      title:"London 79 (Destiny Tour)", poster:"london79.jpg", source:"", type:"hls", category:"live", tier:"pro" },
  { id:"ny01pro",       title:"New York 2001", poster:"ny01pro.jpg",       source:"", type:"hls", category:"live", tier:"pro" },
  { id:"nysept10-01ama",title:"New York 2001 (Sept 10)", poster:"nysept10-01ama.jpg", source:"", type:"hls", category:"live", tier:"am" },
  { id:"kansas84",      title:"Kansas 84",     poster:"kansas84.jpg",      source:"", type:"hls", category:"live", tier:"pro" },
  { id:"ny84",          title:"New York 84",   poster:"ny84.jpg",          source:"", type:"hls", category:"live", tier:"am"  },
  { id:"dallas84",      title:"Dallas 84",     poster:"dallas84.jpg",      source:"", type:"hls", category:"live", tier:"pro" },

  // weitere AM-Markierungen laut deiner Liste
  { id:"mexico93",      title:"Mexico 93",     poster:"mexico93.jpg",      source:"", type:"hls", category:"live", tier:"am"  },
  { id:"amsterdam96",   title:"Amsterdam 96",  poster:"amsterdam96.jpg",   source:"", type:"hls", category:"live", tier:"am"  },
  { id:"tokyo97",       title:"Tokyo 97",      poster:"tokyo97.jpg",       source:"", type:"hls", category:"live", tier:"am"  },
  { id:"hockenheim97",  title:"Hockenheim 97", poster:"hockenheim97.jpg",  source:"", type:"hls", category:"live", tier:"am"  },
  { id:"gelsenkirchen97",title:"Gelsenkirchen 97",poster:"gelsenkirchen97.jpg",source:"", type:"hls", category:"live", tier:"am" },
  { id:"budapest96",    title:"Budapest 96",   poster:"budapest96.jpg",    source:"", type:"hls", category:"live", tier:"am"  },
  { id:"ostende97",     title:"Ostende 97",    poster:"ostende97.jpg",     source:"", type:"hls", category:"live", tier:"am"  },
  { id:"badreports89",     title:"Bad Tour Report 1989",    poster:"badreports89.jpg",     source:"", type:"hls", category:"live", tier:"pro" },
  { id:"badreports87",     title:"Bad Tour Report 1987",    poster:"badreports87.jpg",     source:"", type:"hls", category:"live", tier:"pro" },
  { id:"badreports88",     title:"Bad Tour Report 1988",    poster:"badreports88.jpg",     source:"", type:"hls", category:"live", tier:"pro" },
  { id:"dangerousreports92",title:"Dangerous Tour Report 1992",poster:"dangerousreports92.jpg",source:"",type:"hls",category:"live",tier:"pro" },
  { id:"dangerousreports93",title:"Dangerous Tour Report 1993",poster:"dangerousreports93.jpg",source:"",type:"hls",category:"live",tier:"pro" },
  { id:"historyreports96", title:"History Tour Report 1996",poster:"historyreports96.jpg",source:"",type:"hls",category:"live",tier:"pro" },
  { id:"historyreports97", title:"History Tour Report 1997",poster:"historyreports97.jpg",source:"",type:"hls",category:"live",tier:"pro" },
  { id:"tokyo88",          title:"Tokyo 1988",              poster:"tokyo88.jpg",          source:"",type:"hls",category:"live",tier:"pro" }
];